version: '3.8'

services:
  app:
    build:
      args:
        user: weroad
        uid: 1000
      context: .
      dockerfile: deploy/Dockerfile
    image: alex-weroad-app
    container_name: alex_weroad_app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
      - /var/www/vendor/
    networks:
      - alex-weroad-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - alex-weroad-network

  nginx:
    image: nginx:alpine
    container_name: alex_weroad_nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - alex-weroad-network

  mysql:
    image: mysql:8.0
    container_name: alex_weroad_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./deploy/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - alex-weroad-network

  swaggerui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /var/www/swagger.json
    volumes:
      - ./public:/var/www
    ports:
      - "8082:8080"
    networks:
      - alex-weroad-network

networks:
  alex-weroad-network:
    driver: bridge

volumes:
  mysqldata:
