### Set variables
@baseUrl = http://localhost:81

### login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@weroad.com",
    "password": "admin@weroad.com"
}

> {%
    client.global.set("auth_token", response.body.data.token);
%}

### create travel
POST {{baseUrl}}/api/v1/admin/travels
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "maramures 360",
    "numberOfDays": 3,
    "description": "Lorem ipsum ....",
    "isPublic": true,
    "moods": {
        "nature": 100,
        "relax": 30,
        "history": 10,
        "culture": 20,
        "party": 10
    }
}

> {%
    client.global.set("latest_travel_id", response.body.data.id);
%}

### create tour
POST {{baseUrl}}/api/v1/admin/tours
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "maramures 360",
    "travelId": "{{latest_travel_id}}",
    "price": 6969,
    "startingDate": "2024-03-12",
    "endingDate": "2024-03-27"
}

